spring:
  application:
    name: chat
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/chat?authSource=admin
      uuid-representation: standard
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        streamable-http:
          connections:
            server1:
              url: http://localhost:8082
              endpoint: /mcp

server:
  servlet:
    context-path: /agent_conversation/v1

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.ai: DEBUG